//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.Hareketler = new HashSet<Hareketler>();
        }
    
        public int KitapID { get; set; }
        public string KitapAD { get; set; }
        public Nullable<byte> KategoriID { get; set; }
        public Nullable<int> YazarID { get; set; }
        public string BasimYili { get; set; }
        public string YayinEvi { get; set; }
        public string Sayfa { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string KitapResim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hareketler> Hareketler { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
    }
}
